// Departamentos de Colombia con sus principales ciudades/municipios.
// Lista basada en la división político-administrativa (DIVIPOLA); incluye
// capitales y municipios más poblados de cada departamento.
export const CIUDADES_POR_DEPARTAMENTO: Record<string, string[]> = {
  Amazonas: ["Leticia", "Puerto Nariño"],
  Antioquia: [
    "Medellín",
    "Bello",
    "Itagüí",
    "Envigado",
    "Apartadó",
    "Turbo",
    "Rionegro",
    "Sabaneta",
    "La Estrella",
    "Copacabana",
    "Caldas",
    "Girardota",
    "Caucasia",
    "Necoclí",
    "Chigorodó",
  ],
  Arauca: ["Arauca", "Arauquita", "Saravena", "Tame", "Fortul"],
  Atlántico: [
    "Barranquilla",
    "Soledad",
    "Malambo",
    "Sabanalarga",
    "Puerto Colombia",
    "Galapa",
    "Baranoa",
  ],
  "Bogotá D.C.": ["Bogotá D.C."],
  Bolívar: [
    "Cartagena",
    "Magangué",
    "Turbaco",
    "Arjona",
    "El Carmen de Bolívar",
    "María la Baja",
  ],
  Boyacá: [
    "Tunja",
    "Duitama",
    "Sogamoso",
    "Chiquinquirá",
    "Paipa",
    "Puerto Boyacá",
    "Villa de Leyva",
  ],
  Caldas: [
    "Manizales",
    "La Dorada",
    "Chinchiná",
    "Villamaría",
    "Riosucio",
    "Anserma",
  ],
  Caquetá: ["Florencia", "San Vicente del Caguán", "Puerto Rico", "El Doncello"],
  Casanare: ["Yopal", "Aguazul", "Villanueva", "Tauramena", "Paz de Ariporo"],
  Cauca: [
    "Popayán",
    "Santander de Quilichao",
    "Puerto Tejada",
    "Patía (El Bordo)",
    "Piendamó",
    "Miranda",
  ],
  Cesar: [
    "Valledupar",
    "Aguachica",
    "Agustín Codazzi",
    "Bosconia",
    "La Jagua de Ibirico",
    "Chimichagua",
  ],
  Chocó: ["Quibdó", "Istmina", "Riosucio", "Tadó", "Acandí", "Condoto"],
  Córdoba: [
    "Montería",
    "Cereté",
    "Sahagún",
    "Lorica",
    "Montelíbano",
    "Planeta Rica",
    "Tierralta",
  ],
  Cundinamarca: [
    "Soacha",
    "Facatativá",
    "Zipaquirá",
    "Fusagasugá",
    "Chía",
    "Mosquera",
    "Madrid",
    "Funza",
    "Cajicá",
    "Girardot",
    "Ubaté",
    "Cota",
    "La Calera",
  ],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare", "El Retorno", "Calamar"],
  Huila: ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre"],
  "La Guajira": [
    "Riohacha",
    "Maicao",
    "Uribia",
    "Manaure",
    "San Juan del Cesar",
    "Fonseca",
  ],
  Magdalena: [
    "Santa Marta",
    "Ciénaga",
    "Fundación",
    "Zona Bananera",
    "El Banco",
    "Plato",
  ],
  Meta: [
    "Villavicencio",
    "Acacías",
    "Granada",
    "Puerto López",
    "La Macarena",
    "Restrepo",
  ],
  Nariño: ["Pasto", "Tumaco", "Ipiales", "Túquerres", "La Unión", "Samaniego"],
  "Norte de Santander": [
    "Cúcuta",
    "Ocaña",
    "Villa del Rosario",
    "Los Patios",
    "Pamplona",
    "Tibú",
  ],
  Putumayo: [
    "Mocoa",
    "Puerto Asís",
    "Orito",
    "Valle del Guamuez",
    "Villagarzón",
  ],
  Quindío: [
    "Armenia",
    "Calarcá",
    "La Tebaida",
    "Montenegro",
    "Quimbaya",
    "Circasia",
  ],
  Risaralda: [
    "Pereira",
    "Dosquebradas",
    "Santa Rosa de Cabal",
    "La Virginia",
    "Belén de Umbría",
  ],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  Santander: [
    "Bucaramanga",
    "Floridablanca",
    "Girón",
    "Piedecuesta",
    "Barrancabermeja",
    "San Gil",
    "Socorro",
    "Barbosa",
  ],
  Sucre: ["Sincelejo", "Corozal", "Sampués", "San Marcos", "Tolú"],
  Tolima: [
    "Ibagué",
    "Espinal",
    "Melgar",
    "Honda",
    "Líbano",
    "Chaparral",
    "Mariquita",
  ],
  "Valle del Cauca": [
    "Cali",
    "Buenaventura",
    "Palmira",
    "Tuluá",
    "Cartago",
    "Buga",
    "Jamundí",
    "Yumbo",
    "Candelaria",
    "Florida",
    "Zarzal",
  ],
  Vaupés: ["Mitú"],
  Vichada: ["Puerto Carreño", "La Primavera", "Cumaribo"],
};

export const DEPARTAMENTOS_COLOMBIA = Object.keys(CIUDADES_POR_DEPARTAMENTO);
